<?php
  function triangle_tracker_menu() {
    $items = array();
    $items['triangle_tracker'] = array(
      'title' => 'Triangle Tracker',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('triangle_tracker_form'),
      'access callback' => TRUE,
      'type' => MENU_NORMAL_ITEM,
    );
    $items['triangle_tracker_success_page'] = array(
      'title' => 'Success',
      'page callback' => 'triangle_tracker_success',
      'access callback' => TRUE,
      'type' => MENU_CALLBACK,
    );
    return $items;
  }

  function triangle_tracker_form() {
    $form['side1'] = array(
      '#title' => 'Side 1',
      '#type' => 'textfield',
      '#description' => t('Enter the first side of the triangle.'),
      '#element_validate' => array('element_validate_integer_positive'),
      '#required' => TRUE,
    );
    $form['side2'] = array(
      '#title' => 'Side 2',
      '#type' => 'textfield',
      '#description' => t('Enter the second side of the triangle.'),
      '#element_validate' => array('element_validate_integer_positive'),
      '#required' => TRUE,
    );
    $form['side3'] = array(
      '#title' => 'Side 3',
      '#type' => 'textfield',
      '#description' => t('Enter the third side of the triangle.'),
      '#element_validate' => array('element_validate_integer_positive'),
      '#required' => TRUE,
    );
    $form['submit'] = array(
      '#type' => 'submit',
      '#value' => 'OK',
    );
    return $form;
  }

  function triangle_tracker_form_submit($form, &$form_state) {
    $side1 = $form_state['values']['side1'];
    $side2 = $form_state['values']['side2'];
    $side3 = $form_state['values']['side3'];
    $output = "";

    if ((($side1 + $side2) <= $side3) || (($side1 + $side3) <= $side2) || (($side3 + $side2) <= $side1)) {
      $output = "Not a triangle. Any one side can NOT be greater than or equal to the sum of the other two sides.";
    } elseif (($side1 == $side2) && ($side1 == $side3)) {
        $output = "It's an equilateral triangle!";
    }   elseif ((($side1 == $side2) && ($side1 != $side3)) || (($side2 ==   $side3) && ($side2 != $side1)) || (($side1 == $side3) && ($side1 != $side2))) {
        $output = "It's an isoceles triangle!";
    }
       elseif (!(($side1 == $side2) == $side3)) {
        $output = "It's a scalene triangle!";
    }

    $_SESSION['triangle_output'] = $output;
    $form_state['redirect'] = 'triangle_tracker_success_page';
  }

  function triangle_tracker_success() {
    $output = $_SESSION['triangle_output'];
    return $output;
  }
